
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 31 02:46:16 EDT 2010
//----------------------------------------------------

package pish;

/** CUP generated interface containing symbol constants. */
public interface PishSym {
  /* terminals */
  public static final int RSPAREN = 35;
  public static final int STRING_LITERAL = 42;
  public static final int FUNCTION = 24;
  public static final int CHAR = 36;
  public static final int CONST = 23;
  public static final int INTEGER = 37;
  public static final int LPAREN = 32;
  public static final int INT = 43;
  public static final int ARRAY = 22;
  public static final int FORWARD = 21;
  public static final int FOR = 20;
  public static final int MINUS = 30;
  public static final int RPAREN = 33;
  public static final int NOT = 18;
  public static final int SEMICOLON = 19;
  public static final int RECORD = 17;
  public static final int TYPE = 16;
  public static final int OR = 2;
  public static final int COMMA = 27;
  public static final int MULOP = 41;
  public static final int BEGIN = 15;
  public static final int PLUS = 29;
  public static final int ASSIGN = 26;
  public static final int IF = 14;
  public static final int RELOP = 40;
  public static final int ID = 39;
  public static final int DOT = 31;
  public static final int OF = 13;
  public static final int DECIMAL = 44;
  public static final int EOF = 0;
  public static final int EQUAL = 3;
  public static final int error = 1;
  public static final int PROGRAM = 12;
  public static final int REAL = 38;
  public static final int COLON = 28;
  public static final int ELSE = 10;
  public static final int TO = 9;
  public static final int WHILE = 8;
  public static final int THEN = 7;
  public static final int END = 6;
  public static final int DOWNTO = 5;
  public static final int VAR = 4;
  public static final int PROCEDURE = 11;
  public static final int LSPAREN = 34;
  public static final int DO = 25;
}

