#This Assembly Code has been auto-generated by The Mohamad and Tom Pish Compiler.

# Constant Declaration Section
	.data
	WORDS:	.ascii	"'OH MAH WORD\n'"
			.space	44
	STRINGSIZE:	.word	10
	MAX:	.word	100
	ORMIN:	.word	-100
	ANDSPEEDOFLIGHT:	.float	2998000.0
	WHILENAME:	.ascii	"'Alice'"
			.space	20

# Typedef Declaration Section
	.data
	STRING:		.space	36
	STUDENT:		.space	84
	CLASS:		.space	796

# Simple Declaration Section
	.data
	X: 	.float	0
	Y: 	.float	0
	T: 	.word	0
	D: 	.word	0
	MOE: 	.space	84

# Set jump to main to override
.text
.globl MAIN
j MAIN

# SubPrograms Main 

# Program Main 
MAIN:
	li	$v0, 10		# system call code for exit = 10
	syscall		# call operating sys
# New line to make some simulators happy

